//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadados de Relação EDM

[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_categoria_tb_usuario", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_usuario), "tb_categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_categoria), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_categoria1", "tb_categoria", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_categoria), "tb_movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_movimento), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_conta_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_usuario), "tb_conta", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_conta), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_conta1", "tb_conta", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_conta), "tb_movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_movimento), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_empresa_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_usuario), "tb_empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_empresa), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_empresa1", "tb_empresa", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_empresa), "tb_movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_movimento), true)]
[assembly: EdmRelationshipAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_usuario1", "tb_usuario", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(DAO.tb_usuario), "tb_movimento", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(DAO.tb_movimento), true)]

#endregion

namespace DAO
{
    #region Contextos
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    public partial class banco : ObjectContext
    {
        #region Construtores
    
        /// <summary>
        /// Inicializa um novo objeto banco usando a cadeia de conexão localizada na seção 'banco' do arquivo de configuração do aplicativo.
        /// </summary>
        public banco() : base("name=banco", "banco")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto banco.
        /// </summary>
        public banco(string connectionString) : base(connectionString, "banco")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicialize um novo objeto banco.
        /// </summary>
        public banco(EntityConnection connection) : base(connection, "banco")
        {
            this.ContextOptions.LazyLoadingEnabled = false;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos Parciais
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propriedades de ObjectSet
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tb_categoria> tb_categoria
        {
            get
            {
                if ((_tb_categoria == null))
                {
                    _tb_categoria = base.CreateObjectSet<tb_categoria>("tb_categoria");
                }
                return _tb_categoria;
            }
        }
        private ObjectSet<tb_categoria> _tb_categoria;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tb_conta> tb_conta
        {
            get
            {
                if ((_tb_conta == null))
                {
                    _tb_conta = base.CreateObjectSet<tb_conta>("tb_conta");
                }
                return _tb_conta;
            }
        }
        private ObjectSet<tb_conta> _tb_conta;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tb_empresa> tb_empresa
        {
            get
            {
                if ((_tb_empresa == null))
                {
                    _tb_empresa = base.CreateObjectSet<tb_empresa>("tb_empresa");
                }
                return _tb_empresa;
            }
        }
        private ObjectSet<tb_empresa> _tb_empresa;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tb_movimento> tb_movimento
        {
            get
            {
                if ((_tb_movimento == null))
                {
                    _tb_movimento = base.CreateObjectSet<tb_movimento>("tb_movimento");
                }
                return _tb_movimento;
            }
        }
        private ObjectSet<tb_movimento> _tb_movimento;
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        public ObjectSet<tb_usuario> tb_usuario
        {
            get
            {
                if ((_tb_usuario == null))
                {
                    _tb_usuario = base.CreateObjectSet<tb_usuario>("tb_usuario");
                }
                return _tb_usuario;
            }
        }
        private ObjectSet<tb_usuario> _tb_usuario;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tb_categoria. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotb_categoria(tb_categoria tb_categoria)
        {
            base.AddObject("tb_categoria", tb_categoria);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tb_conta. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotb_conta(tb_conta tb_conta)
        {
            base.AddObject("tb_conta", tb_conta);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tb_empresa. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotb_empresa(tb_empresa tb_empresa)
        {
            base.AddObject("tb_empresa", tb_empresa);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tb_movimento. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotb_movimento(tb_movimento tb_movimento)
        {
            base.AddObject("tb_movimento", tb_movimento);
        }
    
        /// <summary>
        /// Método preterido para adicionar um novo objeto ao EntitySet tb_usuario. Em vez disso, experimente usar o método .Add da propriedade ObjectSet&lt;T&gt; associada.
        /// </summary>
        public void AddTotb_usuario(tb_usuario tb_usuario)
        {
            base.AddObject("tb_usuario", tb_usuario);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_financeiro_pedroModel", Name="tb_categoria")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_categoria : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tb_categoria.
        /// </summary>
        /// <param name="id_categoria">Valor inicial da propriedade id_categoria.</param>
        /// <param name="nome_categoria">Valor inicial da propriedade nome_categoria.</param>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        public static tb_categoria Createtb_categoria(global::System.Int32 id_categoria, global::System.String nome_categoria, global::System.Int32 id_usuario)
        {
            tb_categoria tb_categoria = new tb_categoria();
            tb_categoria.id_categoria = id_categoria;
            tb_categoria.nome_categoria = nome_categoria;
            tb_categoria.id_usuario = id_usuario;
            return tb_categoria;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_categoria
        {
            get
            {
                return _id_categoria;
            }
            set
            {
                if (_id_categoria != value)
                {
                    Onid_categoriaChanging(value);
                    ReportPropertyChanging("id_categoria");
                    _id_categoria = StructuralObject.SetValidValue(value, "id_categoria");
                    ReportPropertyChanged("id_categoria");
                    Onid_categoriaChanged();
                }
            }
        }
        private global::System.Int32 _id_categoria;
        partial void Onid_categoriaChanging(global::System.Int32 value);
        partial void Onid_categoriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_categoria
        {
            get
            {
                return _nome_categoria;
            }
            set
            {
                Onnome_categoriaChanging(value);
                ReportPropertyChanging("nome_categoria");
                _nome_categoria = StructuralObject.SetValidValue(value, false, "nome_categoria");
                ReportPropertyChanged("nome_categoria");
                Onnome_categoriaChanged();
            }
        }
        private global::System.String _nome_categoria;
        partial void Onnome_categoriaChanging(global::System.String value);
        partial void Onnome_categoriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_categoria_tb_usuario", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_usuario", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_categoria1", "tb_movimento")]
        public EntityCollection<tb_movimento> tb_movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_movimento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_financeiro_pedroModel", Name="tb_conta")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_conta : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tb_conta.
        /// </summary>
        /// <param name="id_conta">Valor inicial da propriedade id_conta.</param>
        /// <param name="nome_banco">Valor inicial da propriedade nome_banco.</param>
        /// <param name="numero_conta">Valor inicial da propriedade numero_conta.</param>
        /// <param name="saldo_conta">Valor inicial da propriedade saldo_conta.</param>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        public static tb_conta Createtb_conta(global::System.Int32 id_conta, global::System.String nome_banco, global::System.String numero_conta, global::System.Decimal saldo_conta, global::System.Int32 id_usuario)
        {
            tb_conta tb_conta = new tb_conta();
            tb_conta.id_conta = id_conta;
            tb_conta.nome_banco = nome_banco;
            tb_conta.numero_conta = numero_conta;
            tb_conta.saldo_conta = saldo_conta;
            tb_conta.id_usuario = id_usuario;
            return tb_conta;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_conta
        {
            get
            {
                return _id_conta;
            }
            set
            {
                if (_id_conta != value)
                {
                    Onid_contaChanging(value);
                    ReportPropertyChanging("id_conta");
                    _id_conta = StructuralObject.SetValidValue(value, "id_conta");
                    ReportPropertyChanged("id_conta");
                    Onid_contaChanged();
                }
            }
        }
        private global::System.Int32 _id_conta;
        partial void Onid_contaChanging(global::System.Int32 value);
        partial void Onid_contaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_banco
        {
            get
            {
                return _nome_banco;
            }
            set
            {
                Onnome_bancoChanging(value);
                ReportPropertyChanging("nome_banco");
                _nome_banco = StructuralObject.SetValidValue(value, false, "nome_banco");
                ReportPropertyChanged("nome_banco");
                Onnome_bancoChanged();
            }
        }
        private global::System.String _nome_banco;
        partial void Onnome_bancoChanging(global::System.String value);
        partial void Onnome_bancoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String numero_conta
        {
            get
            {
                return _numero_conta;
            }
            set
            {
                Onnumero_contaChanging(value);
                ReportPropertyChanging("numero_conta");
                _numero_conta = StructuralObject.SetValidValue(value, false, "numero_conta");
                ReportPropertyChanged("numero_conta");
                Onnumero_contaChanged();
            }
        }
        private global::System.String _numero_conta;
        partial void Onnumero_contaChanging(global::System.String value);
        partial void Onnumero_contaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal saldo_conta
        {
            get
            {
                return _saldo_conta;
            }
            set
            {
                Onsaldo_contaChanging(value);
                ReportPropertyChanging("saldo_conta");
                _saldo_conta = StructuralObject.SetValidValue(value, "saldo_conta");
                ReportPropertyChanged("saldo_conta");
                Onsaldo_contaChanged();
            }
        }
        private global::System.Decimal _saldo_conta;
        partial void Onsaldo_contaChanging(global::System.Decimal value);
        partial void Onsaldo_contaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_conta_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_usuario", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_conta1", "tb_movimento")]
        public EntityCollection<tb_movimento> tb_movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_movimento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_financeiro_pedroModel", Name="tb_empresa")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_empresa : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tb_empresa.
        /// </summary>
        /// <param name="id_empresa">Valor inicial da propriedade id_empresa.</param>
        /// <param name="nome_empresa">Valor inicial da propriedade nome_empresa.</param>
        /// <param name="endereco_empresa">Valor inicial da propriedade endereco_empresa.</param>
        /// <param name="telefone_empresa">Valor inicial da propriedade telefone_empresa.</param>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        public static tb_empresa Createtb_empresa(global::System.Int32 id_empresa, global::System.String nome_empresa, global::System.String endereco_empresa, global::System.String telefone_empresa, global::System.Int32 id_usuario)
        {
            tb_empresa tb_empresa = new tb_empresa();
            tb_empresa.id_empresa = id_empresa;
            tb_empresa.nome_empresa = nome_empresa;
            tb_empresa.endereco_empresa = endereco_empresa;
            tb_empresa.telefone_empresa = telefone_empresa;
            tb_empresa.id_usuario = id_usuario;
            return tb_empresa;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                if (_id_empresa != value)
                {
                    Onid_empresaChanging(value);
                    ReportPropertyChanging("id_empresa");
                    _id_empresa = StructuralObject.SetValidValue(value, "id_empresa");
                    ReportPropertyChanged("id_empresa");
                    Onid_empresaChanged();
                }
            }
        }
        private global::System.Int32 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int32 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_empresa
        {
            get
            {
                return _nome_empresa;
            }
            set
            {
                Onnome_empresaChanging(value);
                ReportPropertyChanging("nome_empresa");
                _nome_empresa = StructuralObject.SetValidValue(value, false, "nome_empresa");
                ReportPropertyChanged("nome_empresa");
                Onnome_empresaChanged();
            }
        }
        private global::System.String _nome_empresa;
        partial void Onnome_empresaChanging(global::System.String value);
        partial void Onnome_empresaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String endereco_empresa
        {
            get
            {
                return _endereco_empresa;
            }
            set
            {
                Onendereco_empresaChanging(value);
                ReportPropertyChanging("endereco_empresa");
                _endereco_empresa = StructuralObject.SetValidValue(value, false, "endereco_empresa");
                ReportPropertyChanged("endereco_empresa");
                Onendereco_empresaChanged();
            }
        }
        private global::System.String _endereco_empresa;
        partial void Onendereco_empresaChanging(global::System.String value);
        partial void Onendereco_empresaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String telefone_empresa
        {
            get
            {
                return _telefone_empresa;
            }
            set
            {
                Ontelefone_empresaChanging(value);
                ReportPropertyChanging("telefone_empresa");
                _telefone_empresa = StructuralObject.SetValidValue(value, false, "telefone_empresa");
                ReportPropertyChanged("telefone_empresa");
                Ontelefone_empresaChanged();
            }
        }
        private global::System.String _telefone_empresa;
        partial void Ontelefone_empresaChanging(global::System.String value);
        partial void Ontelefone_empresaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_empresa_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_usuario", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_empresa1", "tb_movimento")]
        public EntityCollection<tb_movimento> tb_movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_movimento", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_financeiro_pedroModel", Name="tb_movimento")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_movimento : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tb_movimento.
        /// </summary>
        /// <param name="id_movimento">Valor inicial da propriedade id_movimento.</param>
        /// <param name="data_movimento">Valor inicial da propriedade data_movimento.</param>
        /// <param name="tipo_movimento">Valor inicial da propriedade tipo_movimento.</param>
        /// <param name="valor_movimento">Valor inicial da propriedade valor_movimento.</param>
        /// <param name="id_categoria">Valor inicial da propriedade id_categoria.</param>
        /// <param name="id_conta">Valor inicial da propriedade id_conta.</param>
        /// <param name="id_empresa">Valor inicial da propriedade id_empresa.</param>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        public static tb_movimento Createtb_movimento(global::System.Int32 id_movimento, global::System.DateTime data_movimento, global::System.Int16 tipo_movimento, global::System.Decimal valor_movimento, global::System.Int32 id_categoria, global::System.Int32 id_conta, global::System.Int32 id_empresa, global::System.Int32 id_usuario)
        {
            tb_movimento tb_movimento = new tb_movimento();
            tb_movimento.id_movimento = id_movimento;
            tb_movimento.data_movimento = data_movimento;
            tb_movimento.tipo_movimento = tipo_movimento;
            tb_movimento.valor_movimento = valor_movimento;
            tb_movimento.id_categoria = id_categoria;
            tb_movimento.id_conta = id_conta;
            tb_movimento.id_empresa = id_empresa;
            tb_movimento.id_usuario = id_usuario;
            return tb_movimento;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_movimento
        {
            get
            {
                return _id_movimento;
            }
            set
            {
                if (_id_movimento != value)
                {
                    Onid_movimentoChanging(value);
                    ReportPropertyChanging("id_movimento");
                    _id_movimento = StructuralObject.SetValidValue(value, "id_movimento");
                    ReportPropertyChanged("id_movimento");
                    Onid_movimentoChanged();
                }
            }
        }
        private global::System.Int32 _id_movimento;
        partial void Onid_movimentoChanging(global::System.Int32 value);
        partial void Onid_movimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_movimento
        {
            get
            {
                return _data_movimento;
            }
            set
            {
                Ondata_movimentoChanging(value);
                ReportPropertyChanging("data_movimento");
                _data_movimento = StructuralObject.SetValidValue(value, "data_movimento");
                ReportPropertyChanged("data_movimento");
                Ondata_movimentoChanged();
            }
        }
        private global::System.DateTime _data_movimento;
        partial void Ondata_movimentoChanging(global::System.DateTime value);
        partial void Ondata_movimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int16 tipo_movimento
        {
            get
            {
                return _tipo_movimento;
            }
            set
            {
                Ontipo_movimentoChanging(value);
                ReportPropertyChanging("tipo_movimento");
                _tipo_movimento = StructuralObject.SetValidValue(value, "tipo_movimento");
                ReportPropertyChanged("tipo_movimento");
                Ontipo_movimentoChanged();
            }
        }
        private global::System.Int16 _tipo_movimento;
        partial void Ontipo_movimentoChanging(global::System.Int16 value);
        partial void Ontipo_movimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String obs_movimento
        {
            get
            {
                return _obs_movimento;
            }
            set
            {
                Onobs_movimentoChanging(value);
                ReportPropertyChanging("obs_movimento");
                _obs_movimento = StructuralObject.SetValidValue(value, true, "obs_movimento");
                ReportPropertyChanged("obs_movimento");
                Onobs_movimentoChanged();
            }
        }
        private global::System.String _obs_movimento;
        partial void Onobs_movimentoChanging(global::System.String value);
        partial void Onobs_movimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal valor_movimento
        {
            get
            {
                return _valor_movimento;
            }
            set
            {
                Onvalor_movimentoChanging(value);
                ReportPropertyChanging("valor_movimento");
                _valor_movimento = StructuralObject.SetValidValue(value, "valor_movimento");
                ReportPropertyChanged("valor_movimento");
                Onvalor_movimentoChanged();
            }
        }
        private global::System.Decimal _valor_movimento;
        partial void Onvalor_movimentoChanging(global::System.Decimal value);
        partial void Onvalor_movimentoChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_categoria
        {
            get
            {
                return _id_categoria;
            }
            set
            {
                Onid_categoriaChanging(value);
                ReportPropertyChanging("id_categoria");
                _id_categoria = StructuralObject.SetValidValue(value, "id_categoria");
                ReportPropertyChanged("id_categoria");
                Onid_categoriaChanged();
            }
        }
        private global::System.Int32 _id_categoria;
        partial void Onid_categoriaChanging(global::System.Int32 value);
        partial void Onid_categoriaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_conta
        {
            get
            {
                return _id_conta;
            }
            set
            {
                Onid_contaChanging(value);
                ReportPropertyChanging("id_conta");
                _id_conta = StructuralObject.SetValidValue(value, "id_conta");
                ReportPropertyChanged("id_conta");
                Onid_contaChanged();
            }
        }
        private global::System.Int32 _id_conta;
        partial void Onid_contaChanging(global::System.Int32 value);
        partial void Onid_contaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_empresa
        {
            get
            {
                return _id_empresa;
            }
            set
            {
                Onid_empresaChanging(value);
                ReportPropertyChanging("id_empresa");
                _id_empresa = StructuralObject.SetValidValue(value, "id_empresa");
                ReportPropertyChanged("id_empresa");
                Onid_empresaChanged();
            }
        }
        private global::System.Int32 _id_empresa;
        partial void Onid_empresaChanging(global::System.Int32 value);
        partial void Onid_empresaChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                Onid_usuarioChanging(value);
                ReportPropertyChanging("id_usuario");
                _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                ReportPropertyChanged("id_usuario");
                Onid_usuarioChanged();
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_categoria1", "tb_categoria")]
        public tb_categoria tb_categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_categoria>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_categoria").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_categoria>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_categoria").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_categoria> tb_categoriaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_categoria>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_categoria>("db_financeiro_pedroModel.fk_tb_movimento_tb_categoria1", "tb_categoria", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_conta1", "tb_conta")]
        public tb_conta tb_conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_conta>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_conta").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_conta>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_conta").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_conta> tb_contaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_conta>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_conta>("db_financeiro_pedroModel.fk_tb_movimento_tb_conta1", "tb_conta", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_empresa1", "tb_empresa")]
        public tb_empresa tb_empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_empresa>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_empresa").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_empresa>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_empresa").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_empresa> tb_empresaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_empresa>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_empresa>("db_financeiro_pedroModel.fk_tb_movimento_tb_empresa1", "tb_empresa", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_usuario1", "tb_usuario")]
        public tb_usuario tb_usuario
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_usuario").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_usuario").Value = value;
            }
        }
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<tb_usuario> tb_usuarioReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_usuario");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<tb_usuario>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_usuario", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// Nenhuma Documentação de Metadados disponível.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="db_financeiro_pedroModel", Name="tb_usuario")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tb_usuario : EntityObject
    {
        #region Método de Fábrica
    
        /// <summary>
        /// Crie um novo objeto tb_usuario.
        /// </summary>
        /// <param name="id_usuario">Valor inicial da propriedade id_usuario.</param>
        /// <param name="nome_usuario">Valor inicial da propriedade nome_usuario.</param>
        /// <param name="email_usuario">Valor inicial da propriedade email_usuario.</param>
        /// <param name="senha_usuario">Valor inicial da propriedade senha_usuario.</param>
        public static tb_usuario Createtb_usuario(global::System.Int32 id_usuario, global::System.String nome_usuario, global::System.String email_usuario, global::System.String senha_usuario)
        {
            tb_usuario tb_usuario = new tb_usuario();
            tb_usuario.id_usuario = id_usuario;
            tb_usuario.nome_usuario = nome_usuario;
            tb_usuario.email_usuario = email_usuario;
            tb_usuario.senha_usuario = senha_usuario;
            return tb_usuario;
        }

        #endregion

        #region Propriedades Simples
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_usuario
        {
            get
            {
                return _id_usuario;
            }
            set
            {
                if (_id_usuario != value)
                {
                    Onid_usuarioChanging(value);
                    ReportPropertyChanging("id_usuario");
                    _id_usuario = StructuralObject.SetValidValue(value, "id_usuario");
                    ReportPropertyChanged("id_usuario");
                    Onid_usuarioChanged();
                }
            }
        }
        private global::System.Int32 _id_usuario;
        partial void Onid_usuarioChanging(global::System.Int32 value);
        partial void Onid_usuarioChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nome_usuario
        {
            get
            {
                return _nome_usuario;
            }
            set
            {
                Onnome_usuarioChanging(value);
                ReportPropertyChanging("nome_usuario");
                _nome_usuario = StructuralObject.SetValidValue(value, false, "nome_usuario");
                ReportPropertyChanged("nome_usuario");
                Onnome_usuarioChanged();
            }
        }
        private global::System.String _nome_usuario;
        partial void Onnome_usuarioChanging(global::System.String value);
        partial void Onnome_usuarioChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String email_usuario
        {
            get
            {
                return _email_usuario;
            }
            set
            {
                Onemail_usuarioChanging(value);
                ReportPropertyChanging("email_usuario");
                _email_usuario = StructuralObject.SetValidValue(value, false, "email_usuario");
                ReportPropertyChanged("email_usuario");
                Onemail_usuarioChanged();
            }
        }
        private global::System.String _email_usuario;
        partial void Onemail_usuarioChanging(global::System.String value);
        partial void Onemail_usuarioChanged();
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String senha_usuario
        {
            get
            {
                return _senha_usuario;
            }
            set
            {
                Onsenha_usuarioChanging(value);
                ReportPropertyChanging("senha_usuario");
                _senha_usuario = StructuralObject.SetValidValue(value, false, "senha_usuario");
                ReportPropertyChanged("senha_usuario");
                Onsenha_usuarioChanged();
            }
        }
        private global::System.String _senha_usuario;
        partial void Onsenha_usuarioChanging(global::System.String value);
        partial void Onsenha_usuarioChanged();

        #endregion

        #region Propriedades de Navegação
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_categoria_tb_usuario", "tb_categoria")]
        public EntityCollection<tb_categoria> tb_categoria
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_categoria>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_categoria");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_categoria>("db_financeiro_pedroModel.fk_tb_categoria_tb_usuario", "tb_categoria", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_conta_tb_usuario1", "tb_conta")]
        public EntityCollection<tb_conta> tb_conta
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_conta>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_conta");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_conta>("db_financeiro_pedroModel.fk_tb_conta_tb_usuario1", "tb_conta", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_empresa_tb_usuario1", "tb_empresa")]
        public EntityCollection<tb_empresa> tb_empresa
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_empresa>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_empresa");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_empresa>("db_financeiro_pedroModel.fk_tb_empresa_tb_usuario1", "tb_empresa", value);
                }
            }
        }
    
        /// <summary>
        /// Nenhuma Documentação de Metadados disponível.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("db_financeiro_pedroModel", "fk_tb_movimento_tb_usuario1", "tb_movimento")]
        public EntityCollection<tb_movimento> tb_movimento
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_movimento");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<tb_movimento>("db_financeiro_pedroModel.fk_tb_movimento_tb_usuario1", "tb_movimento", value);
                }
            }
        }

        #endregion

    }

    #endregion

}
